### PR TITLE
Updated vm box to xenial

### PR DESCRIPTION
**Pull request by sferrini**
As @uafio advised I've updated the vm box to `16.04` (xenial)

### CODE REVIEW

**Comment by Grazfather** [comment]
Have you tested destroying and creating VM from scratch with this change?

**Comment by sferrini** [comment]
@Grazfather I'm on the process of creating the VM, it's slow.. But shouldn't be straightforward?

**Comment by Grazfather** [comment]
It should be, but because the apt repos depend on the release, there could be some issues with dependencies.

**Comment by Grazfather** [comment]
Update?

**Comment by sferrini** [comment]
I've some errors but now I don't have time unfortunately to have a closer look.. Sorry, should I close the PR?

**Pull request closed without merging**
